export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS"
export const GET_CITIES_FAIL = "GET_CITIES_FAIL"
export const ADD_CITY_TO_LIST_SUCCESS = "ADD_CITY_TO_LIST_SUCCESS"
export const ADD_CITY_TO_LIST_FAIL = "ADD_CITY_TO_LIST_FAIL"